### ISSUE TITLE
Rethink options and flags

### ISSUE THREAD

**Issue by millette** [millette/got-weed#2]
Introduce options to:

* List all products
* List unavailable products
* List available products
* Fetch more product details (various prices, etc.)
* List and select country/province #4

**Comment by samuelwang48** [comment]
This issue can be broken down to smaller ones. E.g. Fetch more product details - can be a separate task.

We can design a schema first, listing all the interested fields & etc. someone can work on that interface of taking an SKU as the argument.

**Comment by millette** [comment]
Yes, they will be broken down, but first a little discussion about the road ahead is required, not that it should be too complicated.

Schema #5 - first implementation went with the field names as found in the source json. This should take #4 into consideration.

**Comment by millette** [comment]
Something like this:

```
Find out what products are currently in stock at SQDC.

Usage
  $ got-weed <command> <options>

Usage Examples
  $ got-weed products --language=fr
  $ got-weed products --in-stock=yes --language=en
  $ got-weed products --in-stock --language=en
  $ got-weed products --in-stock=no --language=en
  $ got-weed stores
  $ got-weed locations
  $ got-weed products --location=qc # also accepts qu(e|é)bec and sqdc

Commands
  products        List products
  stores          List local stores
  locations       List supported countries and provinces/states

Options
  --in-stock  -s  In stock only; in-stock=no for the reverse
  --language  -l  Language (fr or en), defaults to $LANG or $LANGUAGE
  --version       Output software version
  --help          This help text
```
